# Generated by Django 5.2.17 on 2026-10-05 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('profesor', 'Profesor'), ('alumno', 'Alumno')], default='alumno', max_length=15)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al sitio de administración')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'constraints': [models.CheckConstraint(condition=models.Q(('rol', 'administrador'), ('rut__isnull', False), _connector='OR'), name='usuario_rut_obligatorio_salvo_admin')],
            },
        ),
    ]
